{% set name = "trends_earth_algorithms" %}
{% set version = "2.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ConservationInternational/trends.earth-algorithms/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 76b9d79d3355578706fe9353695e261e59638f275685d64bd7a98e3f96a2f471

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - openpyxl >=3.0.10
    - backoff >=2.1.0
    - marshmallow >=3.18.0
    - marshmallow-dataclass ==8.5.10
    - defusedxml >=0.7.1
    - trends_earth_schemas
    
test:
  imports:
    - te_algorithms


about:
  home: https://github.com/ConservationInternational/trends.earth-algorithms
  license:  MIT
  license_file: LICENSE
  summary: trends.earth-algorithms is a python package to facilitate analyzing remotely-sensed datasets in support of monitoring land degradation.

extra:
  recipe-maintainers:
    - marie59
